//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;
using ExtraClub.ServiceModel;

namespace ExtraClub.Entities
{
    public partial class ExtraEntities : ObjectContext
    {
        public const string ConnectionString = "name=ExtraEntities";
        public const string ContainerName = "ExtraEntities";

        #region Constructors

        public ExtraEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }

        public ExtraEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }

        #endregion

        #region ObjectSet Properties

        public ObjectSet<Company> Companies
        {
            get { return _companies ?? (_companies = CreateObjectSet<Company>("Companies")); }
        }
        private ObjectSet<Company> _companies;

        public ObjectSet<Customer> Customers
        {
            get { return _customers ?? (_customers = CreateObjectSet<Customer>("Customers")); }
        }
        private ObjectSet<Customer> _customers;

        public ObjectSet<Permission> Permissions
        {
            get { return _permissions ?? (_permissions = CreateObjectSet<Permission>("Permissions")); }
        }
        private ObjectSet<Permission> _permissions;

        public ObjectSet<Role> Roles
        {
            get { return _roles ?? (_roles = CreateObjectSet<Role>("Roles")); }
        }
        private ObjectSet<Role> _roles;

        public ObjectSet<User> Users
        {
            get { return _users ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;

        public ObjectSet<UnitType> UnitTypes
        {
            get { return _unitTypes ?? (_unitTypes = CreateObjectSet<UnitType>("UnitTypes")); }
        }
        private ObjectSet<UnitType> _unitTypes;

        public ObjectSet<GoodsCategory> GoodsCategories
        {
            get { return _goodsCategories ?? (_goodsCategories = CreateObjectSet<GoodsCategory>("GoodsCategories")); }
        }
        private ObjectSet<GoodsCategory> _goodsCategories;

        public ObjectSet<Manufacturer> Manufacturers
        {
            get { return _manufacturers ?? (_manufacturers = CreateObjectSet<Manufacturer>("Manufacturers")); }
        }
        private ObjectSet<Manufacturer> _manufacturers;

        public ObjectSet<ProductType> ProductTypes
        {
            get { return _productTypes ?? (_productTypes = CreateObjectSet<ProductType>("ProductTypes")); }
        }
        private ObjectSet<ProductType> _productTypes;

        public ObjectSet<Good> Goods
        {
            get { return _goods ?? (_goods = CreateObjectSet<Good>("Goods")); }
        }
        private ObjectSet<Good> _goods;

        public ObjectSet<DictionaryCategory> DictionaryCategories
        {
            get { return _dictionaryCategories ?? (_dictionaryCategories = CreateObjectSet<DictionaryCategory>("DictionaryCategories")); }
        }
        private ObjectSet<DictionaryCategory> _dictionaryCategories;

        public ObjectSet<DictionaryInfo> DictionaryInfos
        {
            get { return _dictionaryInfos ?? (_dictionaryInfos = CreateObjectSet<DictionaryInfo>("DictionaryInfos")); }
        }
        private ObjectSet<DictionaryInfo> _dictionaryInfos;

        public ObjectSet<OrganizationType> OrganizationTypes
        {
            get { return _organizationTypes ?? (_organizationTypes = CreateObjectSet<OrganizationType>("OrganizationTypes")); }
        }
        private ObjectSet<OrganizationType> _organizationTypes;

        public ObjectSet<Provider> Providers
        {
            get { return _providers ?? (_providers = CreateObjectSet<Provider>("Providers")); }
        }
        private ObjectSet<Provider> _providers;

        public ObjectSet<ProviderPayment> ProviderPayments
        {
            get { return _providerPayments ?? (_providerPayments = CreateObjectSet<ProviderPayment>("ProviderPayments")); }
        }
        private ObjectSet<ProviderPayment> _providerPayments;

        public ObjectSet<Consignment> Consignments
        {
            get { return _consignments ?? (_consignments = CreateObjectSet<Consignment>("Consignments")); }
        }
        private ObjectSet<Consignment> _consignments;

        public ObjectSet<Division> Divisions
        {
            get { return _divisions ?? (_divisions = CreateObjectSet<Division>("Divisions")); }
        }
        private ObjectSet<Division> _divisions;

        public ObjectSet<ConsignmentLine> ConsignmentLines
        {
            get { return _consignmentLines ?? (_consignmentLines = CreateObjectSet<ConsignmentLine>("ConsignmentLines")); }
        }
        private ObjectSet<ConsignmentLine> _consignmentLines;

        public ObjectSet<GoodPrice> GoodPrices
        {
            get { return _goodPrices ?? (_goodPrices = CreateObjectSet<GoodPrice>("GoodPrices")); }
        }
        private ObjectSet<GoodPrice> _goodPrices;

        public ObjectSet<CustomerCard> CustomerCards
        {
            get { return _customerCards ?? (_customerCards = CreateObjectSet<CustomerCard>("CustomerCards")); }
        }
        private ObjectSet<CustomerCard> _customerCards;

        public ObjectSet<CustomerVisit> CustomerVisits
        {
            get { return _customerVisits ?? (_customerVisits = CreateObjectSet<CustomerVisit>("CustomerVisits")); }
        }
        private ObjectSet<CustomerVisit> _customerVisits;

        public ObjectSet<GoodSale> GoodSales
        {
            get { return _goodSales ?? (_goodSales = CreateObjectSet<GoodSale>("GoodSales")); }
        }
        private ObjectSet<GoodSale> _goodSales;

        public ObjectSet<BonusAccount> BonusAccounts
        {
            get { return _bonusAccounts ?? (_bonusAccounts = CreateObjectSet<BonusAccount>("BonusAccounts")); }
        }
        private ObjectSet<BonusAccount> _bonusAccounts;

        public ObjectSet<BarOrder> BarOrders
        {
            get { return _barOrders ?? (_barOrders = CreateObjectSet<BarOrder>("BarOrders")); }
        }
        private ObjectSet<BarOrder> _barOrders;

        public ObjectSet<DepositAccount> DepositAccounts
        {
            get { return _depositAccounts ?? (_depositAccounts = CreateObjectSet<DepositAccount>("DepositAccounts")); }
        }
        private ObjectSet<DepositAccount> _depositAccounts;

        public ObjectSet<Ticket> Tickets
        {
            get { return _tickets ?? (_tickets = CreateObjectSet<Ticket>("Tickets")); }
        }
        private ObjectSet<Ticket> _tickets;

        public ObjectSet<TicketType> TicketTypes
        {
            get { return _ticketTypes ?? (_ticketTypes = CreateObjectSet<TicketType>("TicketTypes")); }
        }
        private ObjectSet<TicketType> _ticketTypes;

        public ObjectSet<TicketPayment> TicketPayments
        {
            get { return _ticketPayments ?? (_ticketPayments = CreateObjectSet<TicketPayment>("TicketPayments")); }
        }
        private ObjectSet<TicketPayment> _ticketPayments;

        public ObjectSet<TicketFreezeReason> TicketFreezeReasons
        {
            get { return _ticketFreezeReasons ?? (_ticketFreezeReasons = CreateObjectSet<TicketFreezeReason>("TicketFreezeReasons")); }
        }
        private ObjectSet<TicketFreezeReason> _ticketFreezeReasons;

        public ObjectSet<TicketFreeze> TicketFreezes
        {
            get { return _ticketFreezes ?? (_ticketFreezes = CreateObjectSet<TicketFreeze>("TicketFreezes")); }
        }
        private ObjectSet<TicketFreeze> _ticketFreezes;

        public ObjectSet<CustomerCardType> CustomerCardTypes
        {
            get { return _customerCardTypes ?? (_customerCardTypes = CreateObjectSet<CustomerCardType>("CustomerCardTypes")); }
        }
        private ObjectSet<CustomerCardType> _customerCardTypes;

        public ObjectSet<GoodActionLine> GoodActionLines
        {
            get { return _goodActionLines ?? (_goodActionLines = CreateObjectSet<GoodActionLine>("GoodActionLines")); }
        }
        private ObjectSet<GoodActionLine> _goodActionLines;

        public ObjectSet<GoodAction> GoodActions
        {
            get { return _goodActions ?? (_goodActions = CreateObjectSet<GoodAction>("GoodActions")); }
        }
        private ObjectSet<GoodAction> _goodActions;

        public ObjectSet<AdvertType> AdvertTypes
        {
            get { return _advertTypes ?? (_advertTypes = CreateObjectSet<AdvertType>("AdvertTypes")); }
        }
        private ObjectSet<AdvertType> _advertTypes;

        public ObjectSet<Treatment> Treatments
        {
            get { return _treatments ?? (_treatments = CreateObjectSet<Treatment>("Treatments")); }
        }
        private ObjectSet<Treatment> _treatments;

        public ObjectSet<TreatmentType> TreatmentTypes
        {
            get { return _treatmentTypes ?? (_treatmentTypes = CreateObjectSet<TreatmentType>("TreatmentTypes")); }
        }
        private ObjectSet<TreatmentType> _treatmentTypes;

        public ObjectSet<TreatmentSeqRest> TreatmentSeqRests
        {
            get { return _treatmentSeqRests ?? (_treatmentSeqRests = CreateObjectSet<TreatmentSeqRest>("TreatmentSeqRests")); }
        }
        private ObjectSet<TreatmentSeqRest> _treatmentSeqRests;

        public ObjectSet<TreatmentEvent> TreatmentEvents
        {
            get { return _treatmentEvents ?? (_treatmentEvents = CreateObjectSet<TreatmentEvent>("TreatmentEvents")); }
        }
        private ObjectSet<TreatmentEvent> _treatmentEvents;

        public ObjectSet<TreatmentProgramLine> TreatmentProgramLines
        {
            get { return _treatmentProgramLines ?? (_treatmentProgramLines = CreateObjectSet<TreatmentProgramLine>("TreatmentProgramLines")); }
        }
        private ObjectSet<TreatmentProgramLine> _treatmentProgramLines;

        public ObjectSet<TreatmentProgram> TreatmentPrograms
        {
            get { return _treatmentPrograms ?? (_treatmentPrograms = CreateObjectSet<TreatmentProgram>("TreatmentPrograms")); }
        }
        private ObjectSet<TreatmentProgram> _treatmentPrograms;

        public ObjectSet<Instalment> Instalments
        {
            get { return _instalments ?? (_instalments = CreateObjectSet<Instalment>("Instalments")); }
        }
        private ObjectSet<Instalment> _instalments;

        public ObjectSet<UnitCharge> UnitCharges
        {
            get { return _unitCharges ?? (_unitCharges = CreateObjectSet<UnitCharge>("UnitCharges")); }
        }
        private ObjectSet<UnitCharge> _unitCharges;

        public ObjectSet<ReportTemplate> ReportTemplates
        {
            get { return _reportTemplates ?? (_reportTemplates = CreateObjectSet<ReportTemplate>("ReportTemplates")); }
        }
        private ObjectSet<ReportTemplate> _reportTemplates;

        public ObjectSet<ContraIndication> ContraIndications
        {
            get { return _contraIndications ?? (_contraIndications = CreateObjectSet<ContraIndication>("ContraIndications")); }
        }
        private ObjectSet<ContraIndication> _contraIndications;

        public ObjectSet<CustomerTarget> CustomerTargets
        {
            get { return _customerTargets ?? (_customerTargets = CreateObjectSet<CustomerTarget>("CustomerTargets")); }
        }
        private ObjectSet<CustomerTarget> _customerTargets;

        public ObjectSet<Anthropometric> Anthropometrics
        {
            get { return _anthropometrics ?? (_anthropometrics = CreateObjectSet<Anthropometric>("Anthropometrics")); }
        }
        private ObjectSet<Anthropometric> _anthropometrics;

        public ObjectSet<DoctorVisit> DoctorVisits
        {
            get { return _doctorVisits ?? (_doctorVisits = CreateObjectSet<DoctorVisit>("DoctorVisits")); }
        }
        private ObjectSet<DoctorVisit> _doctorVisits;

        public ObjectSet<Nutrition> Nutritions
        {
            get { return _nutritions ?? (_nutritions = CreateObjectSet<Nutrition>("Nutritions")); }
        }
        private ObjectSet<Nutrition> _nutritions;

        public ObjectSet<CustomerMeasure> CustomerMeasures
        {
            get { return _customerMeasures ?? (_customerMeasures = CreateObjectSet<CustomerMeasure>("CustomerMeasures")); }
        }
        private ObjectSet<CustomerMeasure> _customerMeasures;

        public ObjectSet<TreatmentConfig> TreatmentConfigs
        {
            get { return _treatmentConfigs ?? (_treatmentConfigs = CreateObjectSet<TreatmentConfig>("TreatmentConfigs")); }
        }
        private ObjectSet<TreatmentConfig> _treatmentConfigs;

        public ObjectSet<TextAction> TextActions
        {
            get { return _textActions ?? (_textActions = CreateObjectSet<TextAction>("TextActions")); }
        }
        private ObjectSet<TextAction> _textActions;

        public ObjectSet<TreatmentTypeGroup> TreatmentTypeGroups
        {
            get { return _treatmentTypeGroups ?? (_treatmentTypeGroups = CreateObjectSet<TreatmentTypeGroup>("TreatmentTypeGroups")); }
        }
        private ObjectSet<TreatmentTypeGroup> _treatmentTypeGroups;

        public ObjectSet<CustomerStatus> CustomerStatuses
        {
            get { return _customerStatuses ?? (_customerStatuses = CreateObjectSet<CustomerStatus>("CustomerStatuses")); }
        }
        private ObjectSet<CustomerStatus> _customerStatuses;

        public ObjectSet<CustomerNotification> CustomerNotifications
        {
            get { return _customerNotifications ?? (_customerNotifications = CreateObjectSet<CustomerNotification>("CustomerNotifications")); }
        }
        private ObjectSet<CustomerNotification> _customerNotifications;

        public ObjectSet<ChildrenRoom> ChildrenRooms
        {
            get { return _childrenRooms ?? (_childrenRooms = CreateObjectSet<ChildrenRoom>("ChildrenRooms")); }
        }
        private ObjectSet<ChildrenRoom> _childrenRooms;

        public ObjectSet<CustomerShelf> CustomerShelves
        {
            get { return _customerShelves ?? (_customerShelves = CreateObjectSet<CustomerShelf>("CustomerShelves")); }
        }
        private ObjectSet<CustomerShelf> _customerShelves;

        public ObjectSet<Solarium> Solariums
        {
            get { return _solariums ?? (_solariums = CreateObjectSet<Solarium>("Solariums")); }
        }
        private ObjectSet<Solarium> _solariums;

        public ObjectSet<SolariumMessage> SolariumMessages
        {
            get { return _solariumMessages ?? (_solariumMessages = CreateObjectSet<SolariumMessage>("SolariumMessages")); }
        }
        private ObjectSet<SolariumMessage> _solariumMessages;

        public ObjectSet<SolariumVisit> SolariumVisits
        {
            get { return _solariumVisits ?? (_solariumVisits = CreateObjectSet<SolariumVisit>("SolariumVisits")); }
        }
        private ObjectSet<SolariumVisit> _solariumVisits;

        public ObjectSet<MinutesCharge> MinutesCharges
        {
            get { return _minutesCharges ?? (_minutesCharges = CreateObjectSet<MinutesCharge>("MinutesCharges")); }
        }
        private ObjectSet<MinutesCharge> _minutesCharges;

        public ObjectSet<ProviderFolder> ProviderFolders
        {
            get { return _providerFolders ?? (_providerFolders = CreateObjectSet<ProviderFolder>("ProviderFolders")); }
        }
        private ObjectSet<ProviderFolder> _providerFolders;

        public ObjectSet<Storehouse> Storehouses
        {
            get { return _storehouses ?? (_storehouses = CreateObjectSet<Storehouse>("Storehouses")); }
        }
        private ObjectSet<Storehouse> _storehouses;

        public ObjectSet<Certificate> Certificates
        {
            get { return _certificates ?? (_certificates = CreateObjectSet<Certificate>("Certificates")); }
        }
        private ObjectSet<Certificate> _certificates;

        public ObjectSet<Rent> Rents
        {
            get { return _rents ?? (_rents = CreateObjectSet<Rent>("Rents")); }
        }
        private ObjectSet<Rent> _rents;

        public ObjectSet<DepositOut> DepositOuts
        {
            get { return _depositOuts ?? (_depositOuts = CreateObjectSet<DepositOut>("DepositOuts")); }
        }
        private ObjectSet<DepositOut> _depositOuts;

        public ObjectSet<Spending> Spendings
        {
            get { return _spendings ?? (_spendings = CreateObjectSet<Spending>("Spendings")); }
        }
        private ObjectSet<Spending> _spendings;

        public ObjectSet<SpendingType> SpendingTypes
        {
            get { return _spendingTypes ?? (_spendingTypes = CreateObjectSet<SpendingType>("SpendingTypes")); }
        }
        private ObjectSet<SpendingType> _spendingTypes;

        public ObjectSet<EmployeeCategory> EmployeeCategories
        {
            get { return _employeeCategories ?? (_employeeCategories = CreateObjectSet<EmployeeCategory>("EmployeeCategories")); }
        }
        private ObjectSet<EmployeeCategory> _employeeCategories;

        public ObjectSet<Job> Jobs
        {
            get { return _jobs ?? (_jobs = CreateObjectSet<Job>("Jobs")); }
        }
        private ObjectSet<Job> _jobs;

        public ObjectSet<Employee> Employees
        {
            get { return _employees ?? (_employees = CreateObjectSet<Employee>("Employees")); }
        }
        private ObjectSet<Employee> _employees;

        public ObjectSet<JobPlacement> JobPlacements
        {
            get { return _jobPlacements ?? (_jobPlacements = CreateObjectSet<JobPlacement>("JobPlacements")); }
        }
        private ObjectSet<JobPlacement> _jobPlacements;

        public ObjectSet<EmployeeVacation> EmployeeVacations
        {
            get { return _employeeVacations ?? (_employeeVacations = CreateObjectSet<EmployeeVacation>("EmployeeVacations")); }
        }
        private ObjectSet<EmployeeVacation> _employeeVacations;

        public ObjectSet<EmployeeTrip> EmployeeTrips
        {
            get { return _employeeTrips ?? (_employeeTrips = CreateObjectSet<EmployeeTrip>("EmployeeTrips")); }
        }
        private ObjectSet<EmployeeTrip> _employeeTrips;

        public ObjectSet<EmployeeDocument> EmployeeDocuments
        {
            get { return _employeeDocuments ?? (_employeeDocuments = CreateObjectSet<EmployeeDocument>("EmployeeDocuments")); }
        }
        private ObjectSet<EmployeeDocument> _employeeDocuments;

        public ObjectSet<EmployeeVisit> EmployeeVisits
        {
            get { return _employeeVisits ?? (_employeeVisits = CreateObjectSet<EmployeeVisit>("EmployeeVisits")); }
        }
        private ObjectSet<EmployeeVisit> _employeeVisits;

        public ObjectSet<VacationList> VacationLists
        {
            get { return _vacationLists ?? (_vacationLists = CreateObjectSet<VacationList>("VacationLists")); }
        }
        private ObjectSet<VacationList> _vacationLists;

        public ObjectSet<VacationPreference> VacationPreferences
        {
            get { return _vacationPreferences ?? (_vacationPreferences = CreateObjectSet<VacationPreference>("VacationPreferences")); }
        }
        private ObjectSet<VacationPreference> _vacationPreferences;

        public ObjectSet<VacationListItem> VacationListItems
        {
            get { return _vacationListItems ?? (_vacationListItems = CreateObjectSet<VacationListItem>("VacationListItems")); }
        }
        private ObjectSet<VacationListItem> _vacationListItems;

        public ObjectSet<EmployeeWorkGraph> EmployeeWorkGraphs
        {
            get { return _employeeWorkGraphs ?? (_employeeWorkGraphs = CreateObjectSet<EmployeeWorkGraph>("EmployeeWorkGraphs")); }
        }
        private ObjectSet<EmployeeWorkGraph> _employeeWorkGraphs;

        public ObjectSet<Holiday> Holidays
        {
            get { return _holidays ?? (_holidays = CreateObjectSet<Holiday>("Holidays")); }
        }
        private ObjectSet<Holiday> _holidays;

        public ObjectSet<SalaryRateTable> SalaryRateTables
        {
            get { return _salaryRateTables ?? (_salaryRateTables = CreateObjectSet<SalaryRateTable>("SalaryRateTables")); }
        }
        private ObjectSet<SalaryRateTable> _salaryRateTables;

        public ObjectSet<SalaryScheme> SalarySchemes
        {
            get { return _salarySchemes ?? (_salarySchemes = CreateObjectSet<SalaryScheme>("SalarySchemes")); }
        }
        private ObjectSet<SalaryScheme> _salarySchemes;

        public ObjectSet<SalarySchemeCoefficient> SalarySchemeCoefficients
        {
            get { return _salarySchemeCoefficients ?? (_salarySchemeCoefficients = CreateObjectSet<SalarySchemeCoefficient>("SalarySchemeCoefficients")); }
        }
        private ObjectSet<SalarySchemeCoefficient> _salarySchemeCoefficients;

        public ObjectSet<SalarySheetRow> SalarySheetRows
        {
            get { return _salarySheetRows ?? (_salarySheetRows = CreateObjectSet<SalarySheetRow>("SalarySheetRows")); }
        }
        private ObjectSet<SalarySheetRow> _salarySheetRows;

        public ObjectSet<SalarySheet> SalarySheets
        {
            get { return _salarySheets ?? (_salarySheets = CreateObjectSet<SalarySheet>("SalarySheets")); }
        }
        private ObjectSet<SalarySheet> _salarySheets;

        public ObjectSet<EmployeePayment> EmployeePayments
        {
            get { return _employeePayments ?? (_employeePayments = CreateObjectSet<EmployeePayment>("EmployeePayments")); }
        }
        private ObjectSet<EmployeePayment> _employeePayments;

        public ObjectSet<Corporate> Corporates
        {
            get { return _corporates ?? (_corporates = CreateObjectSet<Corporate>("Corporates")); }
        }
        private ObjectSet<Corporate> _corporates;

        public ObjectSet<File> Files
        {
            get { return _files ?? (_files = CreateObjectSet<File>("Files")); }
        }
        private ObjectSet<File> _files;

        public ObjectSet<IncomingCallFormButton> IncomingCallFormButtons
        {
            get { return _incomingCallFormButtons ?? (_incomingCallFormButtons = CreateObjectSet<IncomingCallFormButton>("IncomingCallFormButtons")); }
        }
        private ObjectSet<IncomingCallFormButton> _incomingCallFormButtons;

        public ObjectSet<IncomingCallForm> IncomingCallForms
        {
            get { return _incomingCallForms ?? (_incomingCallForms = CreateObjectSet<IncomingCallForm>("IncomingCallForms")); }
        }
        private ObjectSet<IncomingCallForm> _incomingCallForms;

        public ObjectSet<SalesPlan> SalesPlans
        {
            get { return _salesPlans ?? (_salesPlans = CreateObjectSet<SalesPlan>("SalesPlans")); }
        }
        private ObjectSet<SalesPlan> _salesPlans;

        public ObjectSet<Call> Calls
        {
            get { return _calls ?? (_calls = CreateObjectSet<Call>("Calls")); }
        }
        private ObjectSet<Call> _calls;

        public ObjectSet<Task> Tasks
        {
            get { return _tasks ?? (_tasks = CreateObjectSet<Task>("Tasks")); }
        }
        private ObjectSet<Task> _tasks;

        public ObjectSet<ReportInfo> ReportInfos
        {
            get { return _reportInfos ?? (_reportInfos = CreateObjectSet<ReportInfo>("ReportInfos")); }
        }
        private ObjectSet<ReportInfo> _reportInfos;

        public ObjectSet<ReportParameter> ReportParameters
        {
            get { return _reportParameters ?? (_reportParameters = CreateObjectSet<ReportParameter>("ReportParameters")); }
        }
        private ObjectSet<ReportParameter> _reportParameters;

        public ObjectSet<CustomerTargetType> CustomerTargetTypes
        {
            get { return _customerTargetTypes ?? (_customerTargetTypes = CreateObjectSet<CustomerTargetType>("CustomerTargetTypes")); }
        }
        private ObjectSet<CustomerTargetType> _customerTargetTypes;

        public ObjectSet<CompanyFinance> CompanyFinances
        {
            get { return _companyFinances ?? (_companyFinances = CreateObjectSet<CompanyFinance>("CompanyFinances")); }
        }
        private ObjectSet<CompanyFinance> _companyFinances;

        public ObjectSet<DivisionFinance> DivisionFinances
        {
            get { return _divisionFinances ?? (_divisionFinances = CreateObjectSet<DivisionFinance>("DivisionFinances")); }
        }
        private ObjectSet<DivisionFinance> _divisionFinances;

        public ObjectSet<Income> Incomes
        {
            get { return _incomes ?? (_incomes = CreateObjectSet<Income>("Incomes")); }
        }
        private ObjectSet<Income> _incomes;

        public ObjectSet<IncomeType> IncomeTypes
        {
            get { return _incomeTypes ?? (_incomeTypes = CreateObjectSet<IncomeType>("IncomeTypes")); }
        }
        private ObjectSet<IncomeType> _incomeTypes;

        public ObjectSet<LocalSetting> LocalSettings
        {
            get { return _localSettings ?? (_localSettings = CreateObjectSet<LocalSetting>("LocalSettings")); }
        }
        private ObjectSet<LocalSetting> _localSettings;

        public ObjectSet<CustomReport> CustomReports
        {
            get { return _customReports ?? (_customReports = CreateObjectSet<CustomReport>("CustomReports")); }
        }
        private ObjectSet<CustomReport> _customReports;

        public ObjectSet<SettingsFolder> SettingsFolders
        {
            get { return _settingsFolders ?? (_settingsFolders = CreateObjectSet<SettingsFolder>("SettingsFolders")); }
        }
        private ObjectSet<SettingsFolder> _settingsFolders;

        public ObjectSet<CompanySettingsFolder> CompanySettingsFolders
        {
            get { return _companySettingsFolders ?? (_companySettingsFolders = CreateObjectSet<CompanySettingsFolder>("CompanySettingsFolders")); }
        }
        private ObjectSet<CompanySettingsFolder> _companySettingsFolders;

        public ObjectSet<Log> Logs
        {
            get { return _logs ?? (_logs = CreateObjectSet<Log>("Logs")); }
        }
        private ObjectSet<Log> _logs;

        public ObjectSet<SavedReport> SavedReports
        {
            get { return _savedReports ?? (_savedReports = CreateObjectSet<SavedReport>("SavedReports")); }
        }
        private ObjectSet<SavedReport> _savedReports;

        public ObjectSet<TicketTypeLimit> TicketTypeLimits
        {
            get { return _ticketTypeLimits ?? (_ticketTypeLimits = CreateObjectSet<TicketTypeLimit>("TicketTypeLimits")); }
        }
        private ObjectSet<TicketTypeLimit> _ticketTypeLimits;

        public ObjectSet<TicketCorrection> TicketCorrections
        {
            get { return _ticketCorrections ?? (_ticketCorrections = CreateObjectSet<TicketCorrection>("TicketCorrections")); }
        }
        private ObjectSet<TicketCorrection> _ticketCorrections;

        public ObjectSet<AdvertGroup> AdvertGroups
        {
            get { return _advertGroups ?? (_advertGroups = CreateObjectSet<AdvertGroup>("AdvertGroups")); }
        }
        private ObjectSet<AdvertGroup> _advertGroups;

        public ObjectSet<Kinds1C> Kinds1C
        {
            get { return _kinds1C ?? (_kinds1C = CreateObjectSet<Kinds1C>("Kinds1C")); }
        }
        private ObjectSet<Kinds1C> _kinds1C;

        public ObjectSet<Claim> Claims
        {
            get { return _claims ?? (_claims = CreateObjectSet<Claim>("Claims")); }
        }
        private ObjectSet<Claim> _claims;

        public ObjectSet<Anket> Ankets
        {
            get { return _ankets ?? (_ankets = CreateObjectSet<Anket>("Ankets")); }
        }
        private ObjectSet<Anket> _ankets;

        public ObjectSet<AnketTicket> AnketTickets
        {
            get { return _anketTickets ?? (_anketTickets = CreateObjectSet<AnketTicket>("AnketTickets")); }
        }
        private ObjectSet<AnketTicket> _anketTickets;

        public ObjectSet<AnketTreatment> AnketTreatments
        {
            get { return _anketTreatments ?? (_anketTreatments = CreateObjectSet<AnketTreatment>("AnketTreatments")); }
        }
        private ObjectSet<AnketTreatment> _anketTreatments;

        public ObjectSet<AnketAdvert> AnketAdverts
        {
            get { return _anketAdverts ?? (_anketAdverts = CreateObjectSet<AnketAdvert>("AnketAdverts")); }
        }
        private ObjectSet<AnketAdvert> _anketAdverts;

        public ObjectSet<TicketTypesShop> TicketTypesShops
        {
            get { return _ticketTypesShops ?? (_ticketTypesShops = CreateObjectSet<TicketTypesShop>("TicketTypesShops")); }
        }
        private ObjectSet<TicketTypesShop> _ticketTypesShops;

        public ObjectSet<News> News
        {
            get { return _news ?? (_news = CreateObjectSet<News>("News")); }
        }
        private ObjectSet<News> _news;

        public ObjectSet<SshFile> SshFiles
        {
            get { return _sshFiles ?? (_sshFiles = CreateObjectSet<SshFile>("SshFiles")); }
        }
        private ObjectSet<SshFile> _sshFiles;

        public ObjectSet<SshFileTask> SshFileTasks
        {
            get { return _sshFileTasks ?? (_sshFileTasks = CreateObjectSet<SshFileTask>("SshFileTasks")); }
        }
        private ObjectSet<SshFileTask> _sshFileTasks;

        public ObjectSet<CashInOrder> CashInOrders
        {
            get { return _cashInOrders ?? (_cashInOrders = CreateObjectSet<CashInOrder>("CashInOrders")); }
        }
        private ObjectSet<CashInOrder> _cashInOrders;

        public ObjectSet<CashOutOrder> CashOutOrders
        {
            get { return _cashOutOrders ?? (_cashOutOrders = CreateObjectSet<CashOutOrder>("CashOutOrders")); }
        }
        private ObjectSet<CashOutOrder> _cashOutOrders;

        public ObjectSet<CumulativeDiscount> CumulativeDiscounts
        {
            get { return _cumulativeDiscounts ?? (_cumulativeDiscounts = CreateObjectSet<CumulativeDiscount>("CumulativeDiscounts")); }
        }
        private ObjectSet<CumulativeDiscount> _cumulativeDiscounts;

        public ObjectSet<CustomerCrmEvent> CustomerCrmEvents
        {
            get { return _customerCrmEvents ?? (_customerCrmEvents = CreateObjectSet<CustomerCrmEvent>("CustomerCrmEvents")); }
        }
        private ObjectSet<CustomerCrmEvent> _customerCrmEvents;

        public ObjectSet<CustomerGoodsFlow> CustomerGoodsFlows
        {
            get { return _customerGoodsFlows ?? (_customerGoodsFlows = CreateObjectSet<CustomerGoodsFlow>("CustomerGoodsFlows")); }
        }
        private ObjectSet<CustomerGoodsFlow> _customerGoodsFlows;

        public ObjectSet<PackageLine> PackageLines
        {
            get { return _packageLines ?? (_packageLines = CreateObjectSet<PackageLine>("PackageLines")); }
        }
        private ObjectSet<PackageLine> _packageLines;

        public ObjectSet<Package> Packages
        {
            get { return _packages ?? (_packages = CreateObjectSet<Package>("Packages")); }
        }
        private ObjectSet<Package> _packages;

        public ObjectSet<BarDiscount> BarDiscounts
        {
            get { return _barDiscounts ?? (_barDiscounts = CreateObjectSet<BarDiscount>("BarDiscounts")); }
        }
        private ObjectSet<BarDiscount> _barDiscounts;

        public ObjectSet<SmsMessage> SmsMessages
        {
            get { return _smsMessages ?? (_smsMessages = CreateObjectSet<SmsMessage>("SmsMessages")); }
        }
        private ObjectSet<SmsMessage> _smsMessages;

        public ObjectSet<TargetTypeSet> TargetTypeSets
        {
            get { return _targetTypeSets ?? (_targetTypeSets = CreateObjectSet<TargetTypeSet>("TargetTypeSets")); }
        }
        private ObjectSet<TargetTypeSet> _targetTypeSets;

        public ObjectSet<ReportRecurrency> ReportRecurrencies
        {
            get { return _reportRecurrencies ?? (_reportRecurrencies = CreateObjectSet<ReportRecurrency>("ReportRecurrencies")); }
        }
        private ObjectSet<ReportRecurrency> _reportRecurrencies;

        public ObjectSet<RecurrentSentInfo> RecurrentSentInfos
        {
            get { return _recurrentSentInfos ?? (_recurrentSentInfos = CreateObjectSet<RecurrentSentInfo>("RecurrentSentInfos")); }
        }
        private ObjectSet<RecurrentSentInfo> _recurrentSentInfos;

        public ObjectSet<Email> Emails
        {
            get { return _emails ?? (_emails = CreateObjectSet<Email>("Emails")); }
        }
        private ObjectSet<Email> _emails;

        public ObjectSet<DivisionStar> DivisionStars
        {
            get { return _divisionStars ?? (_divisionStars = CreateObjectSet<DivisionStar>("DivisionStars")); }
        }
        private ObjectSet<DivisionStar> _divisionStars;

        public ObjectSet<EmailItem> EmailItems
        {
            get { return _emailItems ?? (_emailItems = CreateObjectSet<EmailItem>("EmailItems")); }
        }
        private ObjectSet<EmailItem> _emailItems;

        #endregion

        #region Function Imports
        public ObjectResult<Nullable<decimal>> GetAvgSpendings(Nullable<System.DateTime> start, Nullable<System.DateTime> end, Nullable<System.Guid> divisionId)
        {

            ObjectParameter startParameter;

            if (start.HasValue)
            {
                startParameter = new ObjectParameter("start", start);
            }
            else
            {
                startParameter = new ObjectParameter("start", typeof(System.DateTime));
            }

            ObjectParameter endParameter;

            if (end.HasValue)
            {
                endParameter = new ObjectParameter("end", end);
            }
            else
            {
                endParameter = new ObjectParameter("end", typeof(System.DateTime));
            }

            ObjectParameter divisionIdParameter;

            if (divisionId.HasValue)
            {
                divisionIdParameter = new ObjectParameter("divisionId", divisionId);
            }
            else
            {
                divisionIdParameter = new ObjectParameter("divisionId", typeof(System.Guid));
            }
            return base.ExecuteFunction<Nullable<decimal>>("GetAvgSpendings", startParameter, endParameter, divisionIdParameter);
        }
        public ObjectResult<wf_GetSiteCustomers_Result> wf_GetSiteCustomers()
        {
            return base.ExecuteFunction<wf_GetSiteCustomers_Result>("wf_GetSiteCustomers");
        }
        public ObjectResult<sp_GetSmsMarketing_Result> sp_GetSmsMarketing()
        {
            return base.ExecuteFunction<sp_GetSmsMarketing_Result>("sp_GetSmsMarketing");
        }
        public ObjectResult<sp_GetSmsBirthday_Result> sp_GetSmsBirthday()
        {
            return base.ExecuteFunction<sp_GetSmsBirthday_Result>("sp_GetSmsBirthday");
        }

        #endregion

    }
}
