//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace ExtraClub.ServiceModel
{
    
    [DataContract]
    [Serializable]
    public partial class CustomerTargetType : INotifyPropertyChanged
    {
    	private bool _deleted;
    
    	[DataMember]
    	public bool Deleted {
    		get { return _deleted; }
    		set {
    			if (value != _deleted) Modified = true;
    			_deleted = value;
    		}
    	}
    
    	private bool _modified = false;
    	public bool Modified{
    		get
    		{
    			return _modified;
    		}
    		set
    		{
    			if (_modified != value)
    			{
    				_modified = value;
    				OnPropertyChanged("Modified");
    			}
    		}
    	}
    
    	[OnDeserialized()]
        private void OnDeserializedMethod(StreamingContext context)
        {
            _modified = false;
    		OnDeserialized();
        }
    
    	partial void OnDeserialized();
    
    	partial void OnPropertyChangedInternal(string propertyName);
    
        #region Primitive Properties
    	[DataMember]
        public virtual System.Guid Id
        {
            get {return _id;}
            set 
    		{ 
    			if(_id != value)
    			{
    				_id = value; 
    				
    				
    
    				OnPropertyChanged("Id");
    			}
    		}
        }
        private System.Guid _id;
    
    
    	[DataMember]
        public virtual string Name
        {
            get {return _name;}
            set 
    		{ 
    			if(_name != value)
    			{
    				_name = value; 
    				
    				
    
    				OnPropertyChanged("Name");
    			}
    		}
        }
        private string _name;
    
    
    	[DataMember]
        public virtual bool IsAvail
        {
            get {return _isAvail;}
            set 
    		{ 
    			if(_isAvail != value)
    			{
    				_isAvail = value; 
    				
    				
    
    				OnPropertyChanged("IsAvail");
    			}
    		}
        }
        private bool _isAvail;
    
    
    	[DataMember]
        public virtual string NameEn
        {
            get {return _nameEn;}
            set 
    		{ 
    			if(_nameEn != value)
    			{
    				_nameEn = value; 
    				
    				
    
    				OnPropertyChanged("NameEn");
    			}
    		}
        }
        private string _nameEn;
    
    

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<CustomerTarget> CustomerTargets
        {
            get
            {
                if (_customerTargets == null)
                {
                    var newCollection = new FixupCollection<CustomerTarget>();
                    newCollection.CollectionChanged += FixupCustomerTargets;
                    _customerTargets = newCollection;
                }
                return _customerTargets;
            }
            set
            {
                if (!ReferenceEquals(_customerTargets, value))
                {
                    var previousValue = _customerTargets as FixupCollection<CustomerTarget>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCustomerTargets;
                    }
                    _customerTargets = value;
                    var newValue = value as FixupCollection<CustomerTarget>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCustomerTargets;
                    }
    				OnPropertyChanged("CustomerTargets");
                }
            }
        }
        private ICollection<CustomerTarget> _customerTargets;
    
        public virtual ICollection<TreatmentConfig> TreatmentConfigs
        {
            get
            {
                if (_treatmentConfigs == null)
                {
                    var newCollection = new FixupCollection<TreatmentConfig>();
                    newCollection.CollectionChanged += FixupTreatmentConfigs;
                    _treatmentConfigs = newCollection;
                }
                return _treatmentConfigs;
            }
            set
            {
                if (!ReferenceEquals(_treatmentConfigs, value))
                {
                    var previousValue = _treatmentConfigs as FixupCollection<TreatmentConfig>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTreatmentConfigs;
                    }
                    _treatmentConfigs = value;
                    var newValue = value as FixupCollection<TreatmentConfig>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTreatmentConfigs;
                    }
    				OnPropertyChanged("TreatmentConfigs");
                }
            }
        }
        private ICollection<TreatmentConfig> _treatmentConfigs;
    
        public virtual ICollection<TargetTypeSet> TargetTypeSets
        {
            get
            {
                if (_targetTypeSets == null)
                {
                    var newCollection = new FixupCollection<TargetTypeSet>();
                    newCollection.CollectionChanged += FixupTargetTypeSets;
                    _targetTypeSets = newCollection;
                }
                return _targetTypeSets;
            }
            set
            {
                if (!ReferenceEquals(_targetTypeSets, value))
                {
                    var previousValue = _targetTypeSets as FixupCollection<TargetTypeSet>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTargetTypeSets;
                    }
                    _targetTypeSets = value;
                    var newValue = value as FixupCollection<TargetTypeSet>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTargetTypeSets;
                    }
    				OnPropertyChanged("TargetTypeSets");
                }
            }
        }
        private ICollection<TargetTypeSet> _targetTypeSets;

        #endregion

        #region Association Fixup
    
        private void FixupCustomerTargets(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CustomerTarget item in e.NewItems)
                {
                    item.CustomerTargetType = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CustomerTarget item in e.OldItems)
                {
                    if (ReferenceEquals(item.CustomerTargetType, this))
                    {
                        item.CustomerTargetType = null;
                    }
                }
            }
        }
    
        private void FixupTreatmentConfigs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (TreatmentConfig item in e.NewItems)
                {
                    if (!item.CustomerTargetTypes.Contains(this))
                    {
                        item.CustomerTargetTypes.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TreatmentConfig item in e.OldItems)
                {
                    if (item.CustomerTargetTypes.Contains(this))
                    {
                        item.CustomerTargetTypes.Remove(this);
                    }
                }
            }
        }
    
        private void FixupTargetTypeSets(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (TargetTypeSet item in e.NewItems)
                {
                    item.CustomerTargetType = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TargetTypeSet item in e.OldItems)
                {
                    if (ReferenceEquals(item.CustomerTargetType, this))
                    {
                        item.CustomerTargetType = null;
                    }
                }
            }
        }

        #endregion

    
    	public event PropertyChangedEventHandler PropertyChanged;
    
    	protected void OnPropertyChanged(string propertyName)
        {
    		Modified = true;
    
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
    		
    		OnPropertyChangedInternal(propertyName);
        }
    }
}
