//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace ExtraClub.ServiceModel
{
    
    [DataContract]
    [Serializable]
    public partial class ProviderFolder : INotifyPropertyChanged
    {
    	private bool _deleted;
    
    	[DataMember]
    	public bool Deleted {
    		get { return _deleted; }
    		set {
    			if (value != _deleted) Modified = true;
    			_deleted = value;
    		}
    	}
    
    	private bool _modified = false;
    	public bool Modified{
    		get
    		{
    			return _modified;
    		}
    		set
    		{
    			if (_modified != value)
    			{
    				_modified = value;
    				OnPropertyChanged("Modified");
    			}
    		}
    	}
    
    	[OnDeserialized()]
        private void OnDeserializedMethod(StreamingContext context)
        {
            _modified = false;
    		OnDeserialized();
        }
    
    	partial void OnDeserialized();
    
    	partial void OnPropertyChangedInternal(string propertyName);
    
        #region Primitive Properties
    	[DataMember]
        public virtual System.Guid Id
        {
            get {return _id;}
            set 
    		{ 
    			if(_id != value)
    			{
    				_id = value; 
    				
    				
    
    				OnPropertyChanged("Id");
    			}
    		}
        }
        private System.Guid _id;
    
    
    	[DataMember]
        public virtual System.Guid CompanyId
        {
            get { return _companyId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_companyId != value)
                    {
                        if (Company != null && Company.CompanyId != value)
                        {
                            Company = null;
                        }
                        _companyId = value;
        
        				OnPropertyChanged("CompanyId");
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private System.Guid _companyId;
    
    
    	[DataMember]
        public virtual System.Guid AuthorId
        {
            get { return _authorId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_authorId != value)
                    {
                        if (CreatedBy != null && CreatedBy.UserId != value)
                        {
                            CreatedBy = null;
                        }
                        _authorId = value;
        
        				OnPropertyChanged("AuthorId");
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private System.Guid _authorId;
    
    
    	[DataMember]
        public virtual System.DateTime CreatedOn
        {
            get {return _createdOn;}
            set 
    		{ 
    			if(_createdOn != value)
    			{
    				_createdOn = value; 
    				
    				_createdOn = DateTime.SpecifyKind(_createdOn, DateTimeKind.Local);
    
    				OnPropertyChanged("CreatedOn");
    			}
    		}
        }
        private System.DateTime _createdOn;
    
    
    	[DataMember]
        public virtual string Name
        {
            get {return _name;}
            set 
    		{ 
    			if(_name != value)
    			{
    				_name = value; 
    				
    				
    
    				OnPropertyChanged("Name");
    			}
    		}
        }
        private string _name;
    
    
    	[DataMember]
        public virtual Nullable<System.Guid> ParentFolderId
        {
            get { return _parentFolderId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_parentFolderId != value)
                    {
                        if (ParentFolder != null && ParentFolder.Id != value)
                        {
                            ParentFolder = null;
                        }
                        _parentFolderId = value;
        
        				OnPropertyChanged("ParentFolderId");
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<System.Guid> _parentFolderId;
    
    

        #endregion

        #region Navigation Properties
    
        public virtual Company Company
        {
            get { return _company; }
            set
            {
                if (!ReferenceEquals(_company, value))
                {
                    var previousValue = _company;
                    _company = value;
                    FixupCompany(previousValue);
                }
            }
        }
        private Company _company;
    
        public virtual ICollection<ProviderFolder> ChildFolders
        {
            get
            {
                if (_childFolders == null)
                {
                    var newCollection = new FixupCollection<ProviderFolder>();
                    newCollection.CollectionChanged += FixupChildFolders;
                    _childFolders = newCollection;
                }
                return _childFolders;
            }
            set
            {
                if (!ReferenceEquals(_childFolders, value))
                {
                    var previousValue = _childFolders as FixupCollection<ProviderFolder>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupChildFolders;
                    }
                    _childFolders = value;
                    var newValue = value as FixupCollection<ProviderFolder>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupChildFolders;
                    }
    				OnPropertyChanged("ChildFolders");
                }
            }
        }
        private ICollection<ProviderFolder> _childFolders;
    
        public virtual ProviderFolder ParentFolder
        {
            get { return _parentFolder; }
            set
            {
                if (!ReferenceEquals(_parentFolder, value))
                {
                    var previousValue = _parentFolder;
                    _parentFolder = value;
                    FixupParentFolder(previousValue);
                }
            }
        }
        private ProviderFolder _parentFolder;
    
        public virtual User CreatedBy
        {
            get { return _createdBy; }
            set
            {
                if (!ReferenceEquals(_createdBy, value))
                {
                    var previousValue = _createdBy;
                    _createdBy = value;
                    FixupCreatedBy(previousValue);
                }
            }
        }
        private User _createdBy;
    
        public virtual ICollection<Provider> Providers
        {
            get
            {
                if (_providers == null)
                {
                    var newCollection = new FixupCollection<Provider>();
                    newCollection.CollectionChanged += FixupProviders;
                    _providers = newCollection;
                }
                return _providers;
            }
            set
            {
                if (!ReferenceEquals(_providers, value))
                {
                    var previousValue = _providers as FixupCollection<Provider>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProviders;
                    }
                    _providers = value;
                    var newValue = value as FixupCollection<Provider>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProviders;
                    }
    				OnPropertyChanged("Providers");
                }
            }
        }
        private ICollection<Provider> _providers;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupCompany(Company previousValue)
        {
            if (previousValue != null && previousValue.ProviderFolders.Contains(this))
            {
                previousValue.ProviderFolders.Remove(this);
            }
    
            if (Company != null)
            {
                if (!Company.ProviderFolders.Contains(this))
                {
                    Company.ProviderFolders.Add(this);
                }
                if (CompanyId != Company.CompanyId)
                {
                    CompanyId = Company.CompanyId;
                }
            }
        }
    
        private void FixupParentFolder(ProviderFolder previousValue)
        {
            if (previousValue != null && previousValue.ChildFolders.Contains(this))
            {
                previousValue.ChildFolders.Remove(this);
            }
    
            if (ParentFolder != null)
            {
                if (!ParentFolder.ChildFolders.Contains(this))
                {
                    ParentFolder.ChildFolders.Add(this);
                }
                if (ParentFolderId != ParentFolder.Id)
                {
                    ParentFolderId = ParentFolder.Id;
                }
            }
            else if (!_settingFK)
            {
                ParentFolderId = null;
            }
        }
    
        private void FixupCreatedBy(User previousValue)
        {
            if (previousValue != null && previousValue.ProviderFolders.Contains(this))
            {
                previousValue.ProviderFolders.Remove(this);
            }
    
            if (CreatedBy != null)
            {
                if (!CreatedBy.ProviderFolders.Contains(this))
                {
                    CreatedBy.ProviderFolders.Add(this);
                }
                if (AuthorId != CreatedBy.UserId)
                {
                    AuthorId = CreatedBy.UserId;
                }
            }
        }
    
        private void FixupChildFolders(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ProviderFolder item in e.NewItems)
                {
                    item.ParentFolder = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProviderFolder item in e.OldItems)
                {
                    if (ReferenceEquals(item.ParentFolder, this))
                    {
                        item.ParentFolder = null;
                    }
                }
            }
        }
    
        private void FixupProviders(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Provider item in e.NewItems)
                {
                    item.ProviderFolder = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Provider item in e.OldItems)
                {
                    if (ReferenceEquals(item.ProviderFolder, this))
                    {
                        item.ProviderFolder = null;
                    }
                }
            }
        }

        #endregion

    
    	public event PropertyChangedEventHandler PropertyChanged;
    
    	protected void OnPropertyChanged(string propertyName)
        {
    		Modified = true;
    
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
    		
    		OnPropertyChangedInternal(propertyName);
        }
    }
}
