//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace ExtraClub.ServiceModel
{
    
    [DataContract]
    [Serializable]
    public partial class TicketFreeze : INotifyPropertyChanged
    {
    	private bool _deleted;
    
    	[DataMember]
    	public bool Deleted {
    		get { return _deleted; }
    		set {
    			if (value != _deleted) Modified = true;
    			_deleted = value;
    		}
    	}
    
    	private bool _modified = false;
    	public bool Modified{
    		get
    		{
    			return _modified;
    		}
    		set
    		{
    			if (_modified != value)
    			{
    				_modified = value;
    				OnPropertyChanged("Modified");
    			}
    		}
    	}
    
    	[OnDeserialized()]
        private void OnDeserializedMethod(StreamingContext context)
        {
            _modified = false;
    		OnDeserialized();
        }
    
    	partial void OnDeserialized();
    
    	partial void OnPropertyChangedInternal(string propertyName);
    
        #region Primitive Properties
    	[DataMember]
        public virtual System.Guid Id
        {
            get {return _id;}
            set 
    		{ 
    			if(_id != value)
    			{
    				_id = value; 
    				
    				
    
    				OnPropertyChanged("Id");
    			}
    		}
        }
        private System.Guid _id;
    
    
    	[DataMember]
        public virtual System.Guid TicketId
        {
            get { return _ticketId; }
            set
            {
                if (_ticketId != value)
                {
                    if (Ticket != null && Ticket.Id != value)
                    {
                        Ticket = null;
                    }
                    _ticketId = value;
    
    				OnPropertyChanged("TicketId");
                }
            }
        }
        private System.Guid _ticketId;
    
    
    	[DataMember]
        public virtual System.DateTime StartDate
        {
            get {return _startDate;}
            set 
    		{ 
    			if(_startDate != value)
    			{
    				_startDate = value; 
    				
    				_startDate = DateTime.SpecifyKind(_startDate, DateTimeKind.Local);
    
    				OnPropertyChanged("StartDate");
    			}
    		}
        }
        private System.DateTime _startDate;
    
    
    	[DataMember]
        public virtual System.DateTime FinishDate
        {
            get {return _finishDate;}
            set 
    		{ 
    			if(_finishDate != value)
    			{
    				_finishDate = value; 
    				
    				_finishDate = DateTime.SpecifyKind(_finishDate, DateTimeKind.Local);
    
    				OnPropertyChanged("FinishDate");
    			}
    		}
        }
        private System.DateTime _finishDate;
    
    
    	[DataMember]
        public virtual System.Guid TicketFreezeReasonId
        {
            get { return _ticketFreezeReasonId; }
            set
            {
                if (_ticketFreezeReasonId != value)
                {
                    if (TicketFreezeReason != null && TicketFreezeReason.Id != value)
                    {
                        TicketFreezeReason = null;
                    }
                    _ticketFreezeReasonId = value;
    
    				OnPropertyChanged("TicketFreezeReasonId");
                }
            }
        }
        private System.Guid _ticketFreezeReasonId;
    
    
    	[DataMember]
        public virtual string Comment
        {
            get {return _comment;}
            set 
    		{ 
    			if(_comment != value)
    			{
    				_comment = value; 
    				
    				
    
    				OnPropertyChanged("Comment");
    			}
    		}
        }
        private string _comment;
    
    
    	[DataMember]
        public virtual System.Guid AuthorId
        {
            get { return _authorId; }
            set
            {
                if (_authorId != value)
                {
                    if (CreatedBy != null && CreatedBy.UserId != value)
                    {
                        CreatedBy = null;
                    }
                    _authorId = value;
    
    				OnPropertyChanged("AuthorId");
                }
            }
        }
        private System.Guid _authorId;
    
    
    	[DataMember]
        public virtual System.DateTime CreatedOn
        {
            get {return _createdOn;}
            set 
    		{ 
    			if(_createdOn != value)
    			{
    				_createdOn = value; 
    				
    				_createdOn = DateTime.SpecifyKind(_createdOn, DateTimeKind.Local);
    
    				OnPropertyChanged("CreatedOn");
    			}
    		}
        }
        private System.DateTime _createdOn;
    
    
    	[DataMember]
        public virtual System.Guid CompanyId
        {
            get {return _companyId;}
            set 
    		{ 
    			if(_companyId != value)
    			{
    				_companyId = value; 
    				
    				
    
    				OnPropertyChanged("CompanyId");
    			}
    		}
        }
        private System.Guid _companyId;
    
    

        #endregion

        #region Navigation Properties
    
        public virtual TicketFreezeReason TicketFreezeReason
        {
            get { return _ticketFreezeReason; }
            set
            {
                if (!ReferenceEquals(_ticketFreezeReason, value))
                {
                    var previousValue = _ticketFreezeReason;
                    _ticketFreezeReason = value;
                    FixupTicketFreezeReason(previousValue);
                }
            }
        }
        private TicketFreezeReason _ticketFreezeReason;
    
        public virtual Ticket Ticket
        {
            get { return _ticket; }
            set
            {
                if (!ReferenceEquals(_ticket, value))
                {
                    var previousValue = _ticket;
                    _ticket = value;
                    FixupTicket(previousValue);
                }
            }
        }
        private Ticket _ticket;
    
        public virtual User CreatedBy
        {
            get { return _createdBy; }
            set
            {
                if (!ReferenceEquals(_createdBy, value))
                {
                    var previousValue = _createdBy;
                    _createdBy = value;
                    FixupCreatedBy(previousValue);
                }
            }
        }
        private User _createdBy;

        #endregion

        #region Association Fixup
    
        private void FixupTicketFreezeReason(TicketFreezeReason previousValue)
        {
            if (previousValue != null && previousValue.TicketFreezes.Contains(this))
            {
                previousValue.TicketFreezes.Remove(this);
            }
    
            if (TicketFreezeReason != null)
            {
                if (!TicketFreezeReason.TicketFreezes.Contains(this))
                {
                    TicketFreezeReason.TicketFreezes.Add(this);
                }
                if (TicketFreezeReasonId != TicketFreezeReason.Id)
                {
                    TicketFreezeReasonId = TicketFreezeReason.Id;
                }
            }
        }
    
        private void FixupTicket(Ticket previousValue)
        {
            if (previousValue != null && previousValue.TicketFreezes.Contains(this))
            {
                previousValue.TicketFreezes.Remove(this);
            }
    
            if (Ticket != null)
            {
                if (!Ticket.TicketFreezes.Contains(this))
                {
                    Ticket.TicketFreezes.Add(this);
                }
                if (TicketId != Ticket.Id)
                {
                    TicketId = Ticket.Id;
                }
            }
        }
    
        private void FixupCreatedBy(User previousValue)
        {
            if (CreatedBy != null)
            {
                if (AuthorId != CreatedBy.UserId)
                {
                    AuthorId = CreatedBy.UserId;
                }
            }
        }

        #endregion

    
    	public event PropertyChangedEventHandler PropertyChanged;
    
    	protected void OnPropertyChanged(string propertyName)
        {
    		Modified = true;
    
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
    		
    		OnPropertyChangedInternal(propertyName);
        }
    }
}
